### ISSUE TITLE
Group view: ability to resize the colum width

### ISSUE THREAD

**Issue by gagarine** [chzesa/tiled-tab-groups#9]
The column have fixed width. Would be nice to be able to resize them.

I don't think a dragging system is the best. Instead a +/- button for "column width" in the group view is perhaps easier to use.

**Comment by chzesa** [comment]
This has been on the to-do list for a while.

The layout can currently be customized by overriding css for the groups view, as shown below, but this is not ideal for most users.

````
/* 3 columns */
#groups {
	grid-template-columns: repeat(auto-fill, calc((100% - 33px) / 3));
}
````
````
/* two 400px wide columns */
#groups {
	grid-template-columns: 400px 400px
}
````

**Comment by fturcheti** [comment]
I use media-queries to make the groups adapt to the window width, so they're not so _fixed_. I've tested different sizes for the columns before I get the styles that work for me:

```css
/* 2 columns for windows smaller than 800px */ 
#groups {
  grid-template-columns: repeat(auto-fill, calc((100% - 33px) / 2));
}
/* 4 columns for windows greater than 800px */
@media (min-width: 800px) {
  #groups {
    grid-template-columns: repeat(auto-fill, calc((100% - 33px) / 4));
  }
}
/* 6 columns for windows greater than 1600px */
@media (min-width: 1600px) {
  #groups {
    grid-template-columns: repeat(auto-fill, calc((100% - 33px) / 6));
  }
}
```

**Comment by Jipok** [comment]
A similar problem with height. With a large number of groups, the elements are compressed too much and it becomes extremely inconvenient to do anything. 
My solution:
```css
#groups {
  display: flex;
  flex-wrap: wrap;
  overflow-y: auto;
}

#groups .group {
  min-height: calc(50% - 1em);
  max-height: calc(100% - 1em);
}
```
If the groups are in one row, then the height will be full screen. In two rows or more, the height will be half the screen. A scrolling bar will appear from the 3+ row.

@chzesa 
I probably wrote css for the first time. But even if implementation details aside, why not take this behavior as standard? 
Without this modification, moving tabs is very inconvenient when there are a large number of groups:
<details> 
  <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/25588359/142685427-e41ee07d-c731-4d18-9491-8afedc103bf5.png)

</details>
